export const clubsData = [
  {
    "id": "cice",
    "name": "CICE",
    "fullName": "Creativity and Innovation Cell in Electronics",
    "description": "The core technical body of the electronics department at JIIT. Focuses on bridging theoretical learning with hands-on experience.",
    "fullDescription": "The Creativity and Innovation Cell in Electronics (CICE) is the core technical body of the electronics department at JIIT. It focuses on bridging theoretical learning with hands-on experience by training students in PCB design, microcontroller development, and practical electronics. CICE encourages innovation through project-based learning, helping students strengthen their concepts and apply them to real-world applications. Through flagship events like VIDYUT and SPARK, CICE fosters a rich ecosystem of innovation, practical learning, and technical excellence.",
    "category": "Technical",
    "icon": "Cpu",
    "color": "from-yellow-500 to-orange-500",
    "iconColor": "text-yellow-400",
    "image": "https://www.jiit.ac.in/uploads/img_b35381647b.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/cice",
    "socials": {
      "website": "https://ciceweb.vercel.app/",
      "instagram": "https://www.instagram.com/cice_jiit/",
      "linkedin": "https://www.linkedin.com/company/creativity-and-innovation-cell-in-electronics/"
    },
    "gallery": [
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_9_05_21_AM_dc8f4561fb.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_9_04_00_AM_330d231b28.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_9_11_12_AM_53e8cd2f8f.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_9_07_59_AM_1_33d18b0956.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_9_05_21_AM_f3583aa793.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_9_02_08_AM_cb40eeee8f.jpeg",
      "https://www.jiit.ac.in/uploads/IMG_8153_d08777a967.jpg",
      "https://www.jiit.ac.in/uploads/DSC_1019_79c7b18bd7.jpg"
    ]
  },
  {
    "id": "dsc",
    "name": "DSC",
    "fullName": "Developers Student Club",
    "description": "A passionate community of student developers, designers, and technology enthusiasts driven by a shared purpose \u2014 to build, innovate, and make a tangible impact through technology.",
    "fullDescription": "Developers Student Club (DSC) at Jaypee Institute of Information Technology, Noida is a passionate community of student developers, designers, and technology enthusiasts driven by a shared purpose \u2014 to build, innovate, and make a tangible impact through technology. Open to students from all years and disciplines, DSC-JIIT offers a collaborative environment where curiosity is encouraged, creativity is nurtured, and learning goes beyond the classroom. Throughout the academic year, DSC organizes foundational workshops in web and mobile development, advanced AI/ML sessions, internal hackathons for SIH, the 48-hour Hackin' Winters hackathon, and events at Synergy 2025.",
    "category": "Technical",
    "icon": "Code",
    "color": "from-blue-500 to-cyan-500",
    "iconColor": "text-blue-400",
    "image": "https://www.jiit.ac.in/uploads/img_8da7b594ef.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/developers-student-club",
    "socials": {
      "instagram": "https://www.instagram.com/dscjiit/",
      "linkedin": "https://www.linkedin.com/company/dscjiit",
      "website": "https://dsc-jiit-development.vercel.app/"
    },
    "gallery": [
      "https://www.jiit.ac.in/uploads/Picture15_d6a2ccb559.jpg",
      "https://www.jiit.ac.in/uploads/Picture19_e61ba83712.jpg",
      "https://www.jiit.ac.in/uploads/Picture16_91cbe668bd.jpg",
      "https://www.jiit.ac.in/uploads/Picture14_9684a93f09.jpg",
      "https://www.jiit.ac.in/uploads/Picture20_e2a93f4485.jpg",
      "https://www.jiit.ac.in/uploads/Picture6_db45bf94b2.jpg",
      "https://www.jiit.ac.in/uploads/Picture15_37c33e9e50.jpg",
      "https://www.jiit.ac.in/uploads/Picture7_7c490f2d40.jpg",
      "https://www.jiit.ac.in/uploads/Picture23_911c7c29e1.jpg",
      "https://www.jiit.ac.in/uploads/Picture12_b84a928bd9.jpg",
      "https://www.jiit.ac.in/uploads/Picture21_365e52597d.jpg",
      "https://www.jiit.ac.in/uploads/Picture22_6b2a3f8eee.jpg",
      "https://www.jiit.ac.in/uploads/Picture13_a7375d6f13.jpg",
      "https://www.jiit.ac.in/uploads/Picture3_ce7e4e2a4f.png",
      "https://www.jiit.ac.in/uploads/Picture4_81d255777d.png",
      "https://www.jiit.ac.in/uploads/Picture17_404dbc34f7.png",
      "https://www.jiit.ac.in/uploads/Picture11_dc12785459.png",
      "https://www.jiit.ac.in/uploads/Picture10_70912c2a82.png",
      "https://www.jiit.ac.in/uploads/Picture8_f663cdcd27.png",
      "https://www.jiit.ac.in/uploads/Picture5_cdae2f9a02.png",
      "https://www.jiit.ac.in/uploads/Picture1_e22f681e0b.png",
      "https://www.jiit.ac.in/uploads/Picture18_0ef390da3c.png",
      "https://www.jiit.ac.in/uploads/Picture2_b3e6af42c5.png",
      "https://www.jiit.ac.in/uploads/Picture9_835dfdee3d.png"
    ]
  },
  {
    "id": "ribose",
    "name": "RIBOSE",
    "fullName": "Resonance in Biotechnologists & Engineers",
    "description": "The technical hub of the Biotechnology Department, has been a vital part of JIIT, Noida, since its inception in 2012.",
    "fullDescription": "RIBOSE (Resonance in Biotechnologists and Engineers), the technical hub of the Biotechnology Department, has been a vital part of Jaypee Institute of Information Technology, Noida, since its inception in 2012. It has consistently served as a platform for students to grow intellectually and creatively, supporting the Institute's mission to cultivate innovation, entrepreneurship, leadership, and sustainable solutions to societal and environmental challenges. RIBOSE is evolving into a vibrant interdisciplinary space exploring space biotechnology, AI in healthcare, bioinformatics, and sustainable technology.",
    "category": "Technical",
    "icon": "Database",
    "color": "from-emerald-500 to-teal-500",
    "iconColor": "text-emerald-400",
    "image": "https://www.jiit.ac.in/uploads/img_c6efe7f194.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/ribose",
    "socials": {
      "linkedin": "https://in.linkedin.com/company/ribose-the-technical-hub-of-biotechnology",
      "instagram": "https://www.instagram.com/ribose.jiit/",
      "facebook": "https://www.facebook.com/groups/RIBOSEjiit/"
    },
    "gallery": [
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_28_55_PM_1a4eca6239.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_28_56_PM_ed857b19ab.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_28_57_PM_81e55c96ab.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_29_00_PM_465628af15.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_29_02_PM_837e7fcd8d.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_28_53_PM_568ac648e0.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_28_59_PM_1_dba32cedc7.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_28_59_PM_d557071356.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_29_03_PM_77c30e1746.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_28_54_PM_9dd8470371.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_28_55_PM_bade7b70d7.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_29_00_PM_1_ff0578e5f8.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_29_01_PM_83ca7d7902.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_28_57_PM_1_7c41378415.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_28_58_PM_1_122ac03c6c.jpeg"
    ]
  },
  {
    "id": "osdc",
    "name": "OSDC",
    "fullName": "Open Source Developers Community",
    "description": "One of the verticals of the JIIT Programming Hub (Dept. of CSE/IT). Focuses on open source development, GSoC, and hackathons.",
    "fullDescription": "Open Source Developers Community (OSDC) is one of the verticals of the JIIT Programming Hub (a technical hub of the Dept. of CSE/IT). With the vision of enhancing the project development skills of students, OSDC conducts regular workshops, meet-ups, and hackathons. Students are encouraged to utilize GitHub to contribute to Open Source and develop projects for GSoC (Google Summer of Code). Since 2016, more than 20 JIIT student projects have been selected for GSoC. OSDC conducts weekly Tuesday workshops and meet-ups covering Git, Linux, JavaScript, Python, and more.",
    "category": "Technical",
    "icon": "Users",
    "color": "from-orange-500 to-pink-500",
    "iconColor": "text-orange-400",
    "image": "https://www.jiit.ac.in/uploads/osdc_thumb_4ed3ee1439.webp",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/open-source-developers-community-osdc",
    "socials": {
      "website": "https://fossunited.org/c/jiit",
      "linkedin": "https://www.linkedin.com/company/osdcjiit/",
      "instagram": "https://www.instagram.com/osdc.dev/"
    },
    "gallery": [
      "https://www.jiit.ac.in/uploads/image12234_aaaba1695b.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_5_31_33_PM_6918d4ec44.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_4_27_15_PM_fc5de97470.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_4_27_16_PM_edb238a8ec.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_4_27_12_PM_1_f27964d7e2.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_4_27_15_PM_copy_9aece9fb5c.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_4_27_14_PM_2245b70407.jpeg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_24_at_4_27_12_PM_13d20e1c99.jpeg"
    ]
  },
  {
    "id": "zencoders",
    "name": "Zencoders",
    "fullName": "Official Coding & Development Hub",
    "description": "The official coding and development hub of JIIT, committed to nurturing creative thinkers, problem solvers, and future-ready developers.",
    "fullDescription": "ZENCODERS is the official coding and development hub of JIIT, committed to nurturing creative thinkers, problem solvers, and future-ready developers. In 2025, ZENCODERS continued its mission to bridge the gap between theoretical knowledge and practical application. Events include a 3-day C Programming Workshop, collaborative learning sessions, project showcases, mentoring meetups, and the flagship 'Sketch to Site' event where students convert static designs into functional websites.",
    "category": "Technical",
    "icon": "Code",
    "color": "from-violet-500 to-indigo-500",
    "iconColor": "text-violet-400",
    "image": "https://www.jiit.ac.in/uploads/img_2cc4576ce0.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/zencoders",
    "socials": {
      "instagram": "https://www.instagram.com/zencodersjiit/",
      "linkedin": "https://www.linkedin.com/company/zencoders"
    },
    "gallery": [
      "https://www.jiit.ac.in/uploads/zen_6_88e30ba690.jpg",
      "https://www.jiit.ac.in/uploads/zen_6_fd9118d8c5.jpg",
      "https://www.jiit.ac.in/uploads/zen_4_ad4c3f1283.jpg",
      "https://www.jiit.ac.in/uploads/zen_5_4d0547bc86.jpg",
      "https://www.jiit.ac.in/uploads/zen_2_78e9cf608d.jpg",
      "https://www.jiit.ac.in/uploads/zen_3_2a32f69434.jpg",
      "https://www.jiit.ac.in/uploads/zen_1_166118a8f7.jpg"
    ]
  },
  {
    "id": "dice",
    "name": "DICE",
    "fullName": "Data, Insights, Computing & Engineering",
    "description": "A newly established hub exploring the rapidly growing fields of data science, analytics, and computational techniques.",
    "fullDescription": "DICE is a newly established hub created with the vision of exploring the rapidly growing fields of data science, analytics, and computational techniques. What makes DICE unique is its strong mathematics-oriented foundation, making it the first hub in the college with a dedicated focus on mathematical thinking, analytical skills, and their practical applications in data-driven technologies. Through DICE, students get opportunities to work on mini-projects, explore emerging technologies, and collaborate across domains.",
    "category": "Technical",
    "icon": "ChartBar",
    "color": "from-cyan-500 to-blue-500",
    "iconColor": "text-cyan-400",
    "image": "https://www.jiit.ac.in/uploads/dice_thumb_1_ecf9d7043a.webp",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/dice",
    "socials": {
      "instagram": "https://www.instagram.com/dice.jiit/"
    },
    "gallery": [
      "https://www.jiit.ac.in/uploads/dice_image_6382181942.webp",
      "https://www.jiit.ac.in/uploads/DICE_2_d6df5e053b.jpeg",
      "https://www.jiit.ac.in/uploads/DICE_4_533fc19396.jpeg",
      "https://www.jiit.ac.in/uploads/DICE_5_b3409d5cd8.jpeg",
      "https://www.jiit.ac.in/uploads/DICE_3_ee3e2f30b1.jpeg",
      "https://www.jiit.ac.in/uploads/DICE_1_b0efc4a2e0.jpeg"
    ]
  },
  {
    "id": "ucr",
    "name": "\u03bcCR",
    "fullName": "Microcontroller-Based Systems and Robotics Hub",
    "description": "JIIT's pioneering platform for students passionate about Robotics, IoT, and automation. Established in 2005.",
    "fullDescription": "The Microcontroller-Based Systems and Robotics Hub (\u03bcCR) is JIIT's pioneering platform for students passionate about Robotics, IoT, and automation. Since its inception in 2005, \u03bcCR has been dedicated to fostering a hands-on learning culture. Through workshops, mentorship, and project-based challenges, students gain experience in Arduino, NodeMCU, ESP32, embedded systems, manual and autonomous robotics, and system design. Flagship event Spectra features hovercraft workshops, robotics track night at OAT, and competitions like Circuit Rush and Machine Mirage.",
    "category": "Technical",
    "icon": "Robot",
    "color": "from-indigo-500 to-purple-500",
    "iconColor": "text-indigo-400",
    "image": "https://www.jiit.ac.in/uploads/img_8d068e258a.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/microcontroller-based-systems-and-robotics-hub",
    "socials": {
      "website": "https://ucrjiit.com/",
      "instagram": "https://www.instagram.com/ucrjiit/",
      "email": "contact@cicr.in"
    },
    "gallery": [
      "https://www.jiit.ac.in/uploads/DSC_0189_c11a8b3454.jpg",
      "https://www.jiit.ac.in/uploads/IMC_1cb7d24989.jpg",
      "https://www.jiit.ac.in/uploads/RP_Exhibition_2_46c564f013.jpg",
      "https://www.jiit.ac.in/uploads/RP_Exhibition_1ae4aedf88.jpg",
      "https://www.jiit.ac.in/uploads/6_7_dc8bbd7b03.jpg",
      "https://www.jiit.ac.in/uploads/1_3_ec591cf7ef.jpg",
      "https://www.jiit.ac.in/uploads/4_11_e622c6aa64.jpg",
      "https://www.jiit.ac.in/uploads/6271787674465583653_84c10486e1.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_08_21_at_20_12_41_763f973b_e757bfefda.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0238_ad6667f97b.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0209_01_473b8b6c1a.JPG",
      "https://www.jiit.ac.in/uploads/6271787674465583676_473434d5f4.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0208_ed2a7934ac.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0160_f0f7704571.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0282_214_bb4f998365.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0036_e912514d6d.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0013_dabe2a78c9.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0302_233_5ab183359a.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0409_ed394794bf.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0028_70fc943f5c.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0067_3a717866ac.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0349_3c60e2e25e.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0030_c28b8906a3.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0189_5821848b56.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0219_87847bb171.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0321_252_9ca1192ec9.JPG",
      "https://www.jiit.ac.in/uploads/IMG_20241003123903_c885b5e244.jpg",
      "https://www.jiit.ac.in/uploads/IMG_2142_9bce61e371.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250821_115846_1f57e5d3c6.jpg",
      "https://www.jiit.ac.in/uploads/Startup_Summit_Project_Exhibition_1_b858c2e277.png",
      "https://www.jiit.ac.in/uploads/DSC_0245_8f037c4d4e.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0329_f4c0fcd010.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0304_2b38f5a697.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0346_d71956bc2d.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0280_d9e95e95b5.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0282_5c01608721.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0236_b69e9de370.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0225_0ca17278ee.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0306_4413b0ddea.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0217_ca9bfd0843.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0187_d78ab829d4.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0495_bf8f2fb27c.JPG"
    ]
  },
  {
    "id": "silica",
    "name": "SILICA",
    "fullName": "Semiconductor Innovation and Learning Initiative for Chip Advancements",
    "description": "A pioneering hub dedicated to fostering knowledge, innovation, and hands-on learning in the field of semiconductors.",
    "fullDescription": "SILICA is a pioneering hub dedicated to fostering knowledge, innovation, and hands-on learning in the field of semiconductors. As the world continues to rely on chips as the backbone of modern technology, SILICA aims to bridge the gap between theory and practice. Participants gain exposure to Semiconductor Fabrication, Embedded Systems, EDA and CAD Tools like Cadence, and Research & Innovation. The name reflects the foundation of semiconductor technology \u2014 silicon \u2014 and stands as a symbol of clarity, strength, and innovation.",
    "category": "Technical",
    "icon": "Cpu",
    "color": "from-sky-500 to-blue-600",
    "iconColor": "text-sky-400",
    "image": "https://www.jiit.ac.in/uploads/img_5169b095be.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/silica",
    "gallery": [
      "https://www.jiit.ac.in/uploads/image1_0dcb41bdef.jpeg",
      "https://www.jiit.ac.in/uploads/iamge4_074b08d217.jpeg",
      "https://www.jiit.ac.in/uploads/image5_a69ec97097.jpeg",
      "https://www.jiit.ac.in/uploads/image2_e2be24bf1f.jpeg",
      "https://www.jiit.ac.in/uploads/image1_72371d6474.jpeg",
      "https://www.jiit.ac.in/uploads/image3_a885c314ee.jpeg"
    ]
  },
  {
    "id": "gamedev",
    "name": "Game Dev Hub",
    "fullName": "Game Development Hub",
    "description": "Since our childhood, we have been undeniably fond of games. This hub channels that passion into creating digital experiences.",
    "fullDescription": "The Game Development Hub brings together students who share a passion for game design, development, and interactive media. From digital games to physical games, they all bring joy as well as a sense of competitiveness. The hub focuses on game engines, programming, art, storytelling, and the creative process behind building engaging gaming experiences.",
    "category": "Technical",
    "icon": "Gamepad",
    "color": "from-rose-500 to-purple-500",
    "iconColor": "text-rose-400",
    "image": "https://www.jiit.ac.in/uploads/img_0ce0f3b7ea.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/game-development-hub",
    "socials": {
      "instagram": "https://www.instagram.com/gamedev_jiit/",
      "linkedin": "https://www.linkedin.com/company/game-development-hub-jiit-noida",
      "website": "https://game-development-hub-jiit.web.app/",
      "facebook": "https://www.facebook.com/jiit.gamedev/"
    },
    "gallery": [
      "https://www.jiit.ac.in/uploads/IMG_20250923_WA_0046_7c5af5fd5e.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250418_WA_0009_2707133331.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250923_WA_0046_7795c6d44c.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250923_WA_0055_ea508e4b24.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250418_WA_0005_72ecd8bf51.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250923_WA_0012_aba2b952c0.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250923_225758_74a074d1bf.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250923_225645_a372e52c4c.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250922_WA_0005_f84cd6d14a.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250923_WA_0015_c2efa5d492.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0368_d17fdad7e5.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250418173542_aea66846e8.jpg",
      "https://www.jiit.ac.in/uploads/IMG_3485_5ba3600642.JPG",
      "https://www.jiit.ac.in/uploads/20241022_171704_231d49175a.jpg",
      "https://www.jiit.ac.in/uploads/20250715_134412_2299975b15.jpg",
      "https://www.jiit.ac.in/uploads/20241022_55340_PM_By_GPS_Map_Camera_95b39afa32.jpg",
      "https://www.jiit.ac.in/uploads/IMG_5444_95ae87114f.JPG",
      "https://www.jiit.ac.in/uploads/IMG_0253_f990fbc65c.jpg",
      "https://www.jiit.ac.in/uploads/IMG_0541_745a960605.jpg"
    ]
  },
  {
    "id": "knuth",
    "name": "KNUTH",
    "fullName": "KNUTH Programming Hub (KPH)",
    "description": "The flagship vertical of the JIIT Programming Hub (Dept. of CSE/IT), dedicated to fostering a strong culture of Competitive Programming.",
    "fullDescription": "KNUTH Programming Hub (KPH) is the flagship vertical of the JIIT Programming Hub (Dept. of CSE/IT), dedicated to fostering a strong culture of Competitive Programming (CP). Named in honor of Donald Knuth, the hub focuses on building algorithmic thinking, coding proficiency, and preparing students for ICPC, Codeforces, CodeChef, LeetCode, and AtCoder. Through weekly contests, topic-wise deep dives, bootcamps, mentorship, and flagship events like EXECUTE and CODERAGE, KPH nurtures both beginners and advanced programmers.",
    "category": "Technical",
    "icon": "Code",
    "color": "from-emerald-500 to-teal-500",
    "iconColor": "text-emerald-400",
    "image": "https://www.jiit.ac.in/uploads/img_1285f1c4f8.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/knuth-programming-hub",
    "socials": {
      "website": "https://knuth-programming-hub.github.io/",
      "instagram": "https://www.instagram.com/knuth_jiit/",
      "facebook": "https://www.facebook.com/groups/jiit.knuth",
      "telegram": "https://t.me/joinchat/LGo0IhZoPRjRjBJHJPf3OA",
      "unstop": "https://unstop.com/c/knuth-programming-hub-jiit-974052"
    },
    "gallery": [
      "https://www.jiit.ac.in/uploads/img_d3cf940cae.jpg"
    ]
  },
  {
    "id": "ieee",
    "name": "IEEE",
    "fullName": "IEEE Student Branch",
    "description": "Fosters a vibrant community of peers, connecting students with experts and industry professionals at the forefront of cutting-edge technology.",
    "fullDescription": "The IEEE Student Branch JIIT fosters a vibrant community of peers, connecting students with experts and industry professionals at the forefront of cutting-edge technology across various technical fields. IEEE hosts events like 'Xenith', 'Enigma', and supports humanitarian engineering via IEEE SIGHT. It is the world's largest technical professional organization's student chapter at JIIT.",
    "category": "Technical",
    "icon": "Globe",
    "color": "from-blue-600 to-indigo-600",
    "iconColor": "text-blue-500",
    "image": "https://www.jiit.ac.in/uploads/img_6cebf5eac3.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/ieee-student-branch",
    "socials": {
      "unstop": "https://unstop.com/c/ieee-student-branch-jiit-noida-966934",
      "facebook": "https://www.facebook.com/ieeesbjiit/",
      "instagram": "https://www.instagram.com/ieeesbjiit/",
      "linkedin": "https://in.linkedin.com/company/ieee-student-branch-jiit"
    },
    "gallery": [
      "https://www.jiit.ac.in/uploads/2_c4559d9781.jpg",
      "https://www.jiit.ac.in/uploads/24_ca1ad3067f.jpg",
      "https://www.jiit.ac.in/uploads/19_a2a8d7addc.jpg",
      "https://www.jiit.ac.in/uploads/14_bc477f5cde.jpg",
      "https://www.jiit.ac.in/uploads/2_20074446f0.jpg",
      "https://www.jiit.ac.in/uploads/25_4a393618da.jpg",
      "https://www.jiit.ac.in/uploads/5_c80c0aec95.jpg",
      "https://www.jiit.ac.in/uploads/4_0c37b22659.jpg",
      "https://www.jiit.ac.in/uploads/17_6f2a601e3f.jpg",
      "https://www.jiit.ac.in/uploads/23_ecb9ea0153.png",
      "https://www.jiit.ac.in/uploads/18_003ba819d9.jpg",
      "https://www.jiit.ac.in/uploads/10_39484093aa.jpg",
      "https://www.jiit.ac.in/uploads/22_ef5c6bd6e0.jpg",
      "https://www.jiit.ac.in/uploads/7_3c0efbd4e9.jpg",
      "https://www.jiit.ac.in/uploads/6_ef4e157c4c.jpg",
      "https://www.jiit.ac.in/uploads/DSC_00420_742d1f9ad8.jpg",
      "https://www.jiit.ac.in/uploads/IMG_3784_6a31b3a4bb.JPG",
      "https://www.jiit.ac.in/uploads/15_1ad818b4e2.jpg",
      "https://www.jiit.ac.in/uploads/IMG_3781_2bef23942e.JPG",
      "https://www.jiit.ac.in/uploads/11_6d28172069.jpg",
      "https://www.jiit.ac.in/uploads/13_2a4aa34856.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0159_1_6c612551fc.jpg"
    ]
  },
  {
    "id": "pageturner",
    "name": "Page Turner Society",
    "fullName": "The Page Turner Society",
    "description": "A vibrant community of students who share a passion for storytelling.",
    "fullDescription": "The Page Turner Society is a vibrant community of students who share a passion for storytelling. The society encourages reading culture through book exchanges, author meetups, and visits to book cafes. Events include 'Wordsmith Hunt', 'Bookapedia', and the 'Hult Prize'.",
    "category": "Literary",
    "icon": "BookOpen",
    "color": "from-amber-500 to-orange-600",
    "iconColor": "text-amber-500",
    "image": "https://www.jiit.ac.in/uploads/pts_thumb_d885b05ddd.webp",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/the-page-turner-society",
    "socials": {
      "facebook": "https://www.facebook.com/thePageTurnerSociety/",
      "instagram": "https://www.instagram.com/thepageturnersociety/"
    },
    "gallery": [
      "https://www.jiit.ac.in/uploads/pts_image_8b5d070bb3.webp",
      "https://www.jiit.ac.in/uploads/DSC_0742_d4ddfa0539.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0868_be6bfe9e0f.jpg",
      "https://www.jiit.ac.in/uploads/20250128_55754_PM_By_GPS_Map_Camera_9ab72d65d0.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0769_85268306f8.jpg",
      "https://www.jiit.ac.in/uploads/20250128_60235_PM_By_GPS_Map_Camera_86f677601f.jpg",
      "https://www.jiit.ac.in/uploads/1000166131_51a04180ab.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0040_1_f29716af9d.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0046_a522138ef2.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0050_b49aa7a064.jpg",
      "https://www.jiit.ac.in/uploads/DSC_06115_c67faadc96.jpg",
      "https://www.jiit.ac.in/uploads/DSC_06123_7ad64c9d3a.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0069_1_1_42d1d401ee.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0827_2bbbfd50e1.jpg"
    ]
  },
  {
    "id": "parola",
    "name": "Parola",
    "fullName": "The Literary Hub of JIIT",
    "description": "The official literary society of JIIT \u2014 a vibrant community of literature enthusiasts, writers, poets, and orators.",
    "fullDescription": "Parola, the official literary society of Jaypee Institute of Information Technology (JIIT), is a vibrant community of literature enthusiasts, writers, poets, and orators. It organizes debating, extempore, and MUNs, along with the 'Jaypee Youth Parliament' and 'Jaypee Model United Nations' (JMUN).",
    "category": "Literary",
    "icon": "Chat",
    "color": "from-blue-400 to-indigo-500",
    "iconColor": "text-blue-400",
    "image": "https://www.jiit.ac.in/uploads/img_16fa3ed099.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/parola-the-literary-hub-of-jiit",
    "socials": {
      "website": "http://www.jaypeemun.org",
      "facebook": "https://www.facebook.com/JaypeeMUN/",
      "instagram": "https://www.instagram.com/jaypeemun/"
    },
    "gallery": [
      "https://www.jiit.ac.in/uploads/ch_267_3a7ec97c4e.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2026_01_30_at_9_13_41_PM_8540081b7a.jpeg",
      "https://www.jiit.ac.in/uploads/ch_162_b0554602c1.jpg",
      "https://www.jiit.ac.in/uploads/ch_344_06abf070f3.jpg",
      "https://www.jiit.ac.in/uploads/ch_108_e100e36214.jpg",
      "https://www.jiit.ac.in/uploads/ch_125_16779b3f5e.jpg",
      "https://www.jiit.ac.in/uploads/ch_267_25bd992123.jpg",
      "https://www.jiit.ac.in/uploads/ch_281_520ac53bfb.jpg",
      "https://www.jiit.ac.in/uploads/ch_349_b198cd082b.jpg",
      "https://www.jiit.ac.in/uploads/ch_289_d1e29fc59c.jpg",
      "https://www.jiit.ac.in/uploads/ch_331_c7b5d02b62.jpg",
      "https://www.jiit.ac.in/uploads/ch_343_e885044846.jpg",
      "https://www.jiit.ac.in/uploads/ch_357_05d8f79652.jpg",
      "https://www.jiit.ac.in/uploads/ch_313_a02e11adec.jpg",
      "https://www.jiit.ac.in/uploads/ch_293_9a5c2d9d08.jpg"
    ]
  },
  {
    "id": "crescendo",
    "name": "Crescendo",
    "fullName": "The Music Hub of JIIT",
    "description": "A family of avid music enthusiasts who perform, promote, and propagate music. An open community that welcomes all musical talents.",
    "fullDescription": "Crescendo is the Music Hub of JIIT \u2014 a family of avid music enthusiasts who perform, promote, and propagate music. An open community that welcomes and motivates fellow students to unleash their musical talents. Hosts events like 'Unplugged', 'Euphonium', and 'Voice of Impressions'.",
    "category": "Performing Arts",
    "icon": "MusicNotes",
    "color": "from-purple-500 to-pink-500",
    "iconColor": "text-purple-400",
    "image": "https://www.jiit.ac.in/uploads/Frame_2147239034_4795a15916.png",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/crescendo-the-music-hub-of-jiit",
    "gallery": [
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_07_21_at_18_34_25_3734eb7a_e4af4a6b5f.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_07_21_at_18_34_25_3734eb7a_93b9d6a166.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_07_21_at_18_36_23_cdc5f4a5_faa5cfd0c6.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0757_77640b3f87.webp",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_07_15_at_00_39_28_2fc4b6c2_6929a61d0c.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_06_21_at_21_06_42_06c20f4b_87990beb78.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_07_21_at_18_30_34_c4332de9_23ee5253b5.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_06_21_at_22_27_12_bf743752_a2636ea76f.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_06_21_at_19_46_47_4d83e805_89b856a3e0.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_07_21_at_18_34_19_caeddabe_0e1c77f74b.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_07_21_at_18_23_53_62a9905f_a6d72cb648.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2024_08_19_at_15_30_42_cb619da6_1ef4149c6d.jpg",
      "https://www.jiit.ac.in/uploads/image_4782efc1cb.png",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2024_09_09_at_20_38_24_bd5fc631_3cf47f3cce.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_03_14_at_4_28_23_PM_d54d09e6f7.jpg",
      "https://www.jiit.ac.in/uploads/IMG_7046_1_f9afc6c559.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_07_21_at_18_28_04_c6fffee1_7e15c03788.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_06_21_at_22_49_32_416e72d7_7995c67382.jpg",
      "https://www.jiit.ac.in/uploads/MG_9576_a5ed3089bd.jpg",
      "https://www.jiit.ac.in/uploads/efawa_a35100f90a.jpg",
      "https://www.jiit.ac.in/uploads/IMG_5036_2_30235c6efa.jpg",
      "https://www.jiit.ac.in/uploads/IMG_1290_7159135fd8.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0122_e6e3fcbd5d.jpg"
    ]
  },
  {
    "id": "thespian",
    "name": "Thespian Circle",
    "fullName": "Dramatics Society",
    "description": "Stars have airs, actors have egos, but artistes are God's own instruments to create and spread beauty through art.",
    "fullDescription": "Thespian Circle is the dramatics society of JIIT. Stars have airs, actors have egos, but artistes are God's own instruments to create and spread beauty through art. The society focuses on social reform through theatrical art, performing stage plays and street plays (Nukkad Natak).",
    "category": "Performing Arts",
    "icon": "Microphone",
    "color": "from-red-500 to-orange-500",
    "iconColor": "text-red-400",
    "image": "https://www.jiit.ac.in/uploads/thespian_circle_drama_81c15b8306.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/thespian-circle-drama",
    "gallery": [
      "https://www.jiit.ac.in/uploads/do_image_ead76ac53a.png",
      "https://www.jiit.ac.in/uploads/dont_image_7d899efaae.png",
      "https://www.jiit.ac.in/uploads/Picture1_add60115ab.png",
      "https://www.jiit.ac.in/uploads/WPS_Photos_1_f6769b870a.jpeg",
      "https://www.jiit.ac.in/uploads/Picture2_b79ee3d045.png",
      "https://www.jiit.ac.in/uploads/DSC_6751_min_d342b1c93a.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0914_1_min_afb0e4bd48.jpg",
      "https://www.jiit.ac.in/uploads/DSC_1471_min_01560a435e.jpg",
      "https://www.jiit.ac.in/uploads/DSC_6670_min_697a2cb97b.JPG",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_07_21_at_6_54_19_PM_min_ed3fc07212.jpeg",
      "https://www.jiit.ac.in/uploads/DSC_0937_1_min_38a06e9ece.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0489_min_550aa0f752.jpg",
      "https://www.jiit.ac.in/uploads/DSC_6808_min_fb6e4a712d.JPG",
      "https://www.jiit.ac.in/uploads/DSC_0062_min_bd1cd35f55.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0125_min_78d3913ed5.jpg",
      "https://www.jiit.ac.in/uploads/MG_9031_min_fba46b0427.jpeg",
      "https://www.jiit.ac.in/uploads/DSC_1964_min_f85c736339.jpg",
      "https://www.jiit.ac.in/uploads/DSC_1942_min_4708a509bd.jpg",
      "https://www.jiit.ac.in/uploads/DSC_8894_min_2d8c34ef70.JPG",
      "https://www.jiit.ac.in/uploads/1743924777466_min_51a3e16252.jpg",
      "https://www.jiit.ac.in/uploads/20221118_175655_min_13a039b174.jpg",
      "https://www.jiit.ac.in/uploads/20240225144945_MG_1278_min_e986f637a0.jpg",
      "https://www.jiit.ac.in/uploads/MG_9143_min_daf6269c42.jpeg",
      "https://www.jiit.ac.in/uploads/DSC_0188_1_min_a391b692ed.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0306_1_min_f7116f8a32.jpg",
      "https://www.jiit.ac.in/uploads/DSC_0161_min_1dfe1d7b2b.JPG"
    ]
  },
  {
    "id": "mmv",
    "name": "MMV",
    "fullName": "Music Made Visible \u2014 Dance Hub",
    "description": "Dance is an expression of body, it coincides with rhythm of our heart and lasts in our soul like a spirit.",
    "fullDescription": "MMV (Music Made Visible) is the dance hub of JIIT. Dance is an expression of body, it coincides with rhythm of our heart and lasts in our soul like a spirit. The hub includes groups for Western dance, Classical dance (Nrityang), and Bhangra (Surkhaab).",
    "category": "Performing Arts",
    "icon": "Lightning",
    "color": "from-rose-500 to-pink-600",
    "iconColor": "text-rose-400",
    "image": "https://www.jiit.ac.in/uploads/mmv_thumb_81d7769903.webp",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/mmv-music-made-visible",
    "gallery": [
      "https://www.jiit.ac.in/uploads/image11_d10847d1ef.jpg",
      "https://www.jiit.ac.in/uploads/music_image_b931ef9515.jpg",
      "https://www.jiit.ac.in/uploads/DSC_8220_ce37d48d71.jpg",
      "https://www.jiit.ac.in/uploads/DSC_09326_b02bdc85df.jpg",
      "https://www.jiit.ac.in/uploads/DSC_09278_beba1f5e0d.jpg",
      "https://www.jiit.ac.in/uploads/DSC_09352_d57e8853f0.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250923_221025_bb7b797f12.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250923_WA_0020_ff88d67d36.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250923_221202_dc4a477c5d.jpg",
      "https://www.jiit.ac.in/uploads/DSC_09294_a8d26d1ced.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250923_221702_668db162dc.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_09_23_at_22_03_55_d8924a51_72ad46ad53.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250923_222050_841e52fb9f.jpg",
      "https://www.jiit.ac.in/uploads/IMG_5156_f76bed9dd5.jpg",
      "https://www.jiit.ac.in/uploads/DSC_1407_e0aa45ecab.jpg",
      "https://www.jiit.ac.in/uploads/IMG_5113_ab6714577b.jpg",
      "https://www.jiit.ac.in/uploads/IMG_20250923_WA_0018_9f3ca103ba.jpg",
      "https://www.jiit.ac.in/uploads/DSC_2726_406f3702ec.jpg",
      "https://www.jiit.ac.in/uploads/DSC_2721_5039c2f89b.jpg",
      "https://www.jiit.ac.in/uploads/DSC_09063_a5eb6852af.jpg",
      "https://www.jiit.ac.in/uploads/DSC_00720_6cc757448f.jpg"
    ]
  },
  {
    "id": "jpeg",
    "name": "JPEG",
    "fullName": "Jaypee Photographic Enthusiasts Guild",
    "description": "The official photography society of JIIT Noida, dedicated to nurturing creative expression and visual storytelling through the lens.",
    "fullDescription": "JPEG (Jaypee Photographic Enthusiasts Guild) is the official photography society of JIIT Noida, dedicated to nurturing creative expression and visual storytelling through the lens. Conducts workshops on DSLR/editing, photo-walks, and exhibitions. Events include '30-30', 'Just Do It', and 'Snap Story'.",
    "category": "Visual Arts",
    "icon": "Camera",
    "color": "from-cyan-500 to-blue-500",
    "iconColor": "text-cyan-400",
    "image": "https://www.jiit.ac.in/uploads/img_ba7db94abf.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/jaypee-photographic-enthusiasts-guild",
    "gallery": [
      "https://www.jiit.ac.in/uploads/25_577b24a3b0.jpg",
      "https://www.jiit.ac.in/uploads/2_78f2c4432f.jpg",
      "https://www.jiit.ac.in/uploads/8_a88add8f2f.jpg",
      "https://www.jiit.ac.in/uploads/11_fc0729b423.jpg",
      "https://www.jiit.ac.in/uploads/19_c047dc8d7b.jpg",
      "https://www.jiit.ac.in/uploads/22_b313a0c10e.jpg",
      "https://www.jiit.ac.in/uploads/14_c6302f175c.jpg",
      "https://www.jiit.ac.in/uploads/15_66c3102a0c.jpg",
      "https://www.jiit.ac.in/uploads/12_e3e39efd7a.jpg",
      "https://www.jiit.ac.in/uploads/7_f86a196c84.jpg",
      "https://www.jiit.ac.in/uploads/18_67fd146370.jpg",
      "https://www.jiit.ac.in/uploads/10_ae6c1c4c28.jpg",
      "https://www.jiit.ac.in/uploads/5_e1ee24bc6f.jpg",
      "https://www.jiit.ac.in/uploads/6_71f1239e56.jpg",
      "https://www.jiit.ac.in/uploads/23_cd6aa859b5.jpg",
      "https://www.jiit.ac.in/uploads/4_e6d57b902e.jpg",
      "https://www.jiit.ac.in/uploads/9_bb4859080c.jpg",
      "https://www.jiit.ac.in/uploads/24_806cf2ec53.jpg",
      "https://www.jiit.ac.in/uploads/25_60dddfb789.jpg",
      "https://www.jiit.ac.in/uploads/3_b1556e6d24.jpg",
      "https://www.jiit.ac.in/uploads/21_7b567a0cb9.jpg",
      "https://www.jiit.ac.in/uploads/26_976787d111.JPG",
      "https://www.jiit.ac.in/uploads/27_88dded5419.PNG",
      "https://www.jiit.ac.in/uploads/13_72231c5439.jpeg",
      "https://www.jiit.ac.in/uploads/20_092bee949e.jpeg",
      "https://www.jiit.ac.in/uploads/1_13133a723f.jpeg",
      "https://www.jiit.ac.in/uploads/16_c91ff22a65.jpg",
      "https://www.jiit.ac.in/uploads/17_4894f6180c.jpg"
    ]
  },
  {
    "id": "kalakriti",
    "name": "Kalakriti",
    "fullName": "Art and Craft Hub",
    "description": "Where creativity breathes and imagination flows. The official Art and Craft Hub of our college.",
    "fullDescription": "Kalakriti is where creativity breathes and imagination flows. As the official Art and Craft Hub of the college, it unleashes artistic creativity through Sand art, Rangoli, Junk Rangoli, Poster making, and Graffiti. The hub provides a platform for students to express their artistic talents.",
    "category": "Visual Arts",
    "icon": "Palette",
    "color": "from-orange-500 to-red-500",
    "iconColor": "text-orange-400",
    "image": "https://www.jiit.ac.in/uploads/kalakri_thumb_022dc2f80c.webp",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/art-and-cra-hub-kalakri",
    "gallery": [
      "https://www.jiit.ac.in/uploads/image122_60682de2f1.jpg",
      "https://www.jiit.ac.in/uploads/art_1_20d4070f94.webp",
      "https://www.jiit.ac.in/uploads/k_3_b41cb00d9c.webp",
      "https://www.jiit.ac.in/uploads/k_2_7cb2fdd0bd.webp",
      "https://www.jiit.ac.in/uploads/k_6_e64646898f.webp",
      "https://www.jiit.ac.in/uploads/k_4_50df96c718.webp",
      "https://www.jiit.ac.in/uploads/k_7_d856590605.webp",
      "https://www.jiit.ac.in/uploads/k_5_41011aa87e.webp"
    ]
  },
  {
    "id": "business",
    "name": "Economics & Business Hub",
    "fullName": "Economics and Business Hub",
    "description": "Strives to bridge classroom learning with real-world application by creating dynamic platforms for students to explore.",
    "fullDescription": "At the Economics and Business Hub, the focus is on bridging classroom learning with real-world application by creating dynamic platforms for students to explore. The hub cultivates business acumen and hosts events like 'Manager of the Year' and 'Business Buzz'.",
    "category": "Social",
    "icon": "TrendUp",
    "color": "from-slate-500 to-zinc-500",
    "iconColor": "text-slate-400",
    "image": "https://www.jiit.ac.in/uploads/economics_thumb_b1036e4902.webp",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/economics-and-business-hub",
    "gallery": [
      "https://www.jiit.ac.in/uploads/econmica_image_7e907f89ff.webp",
      "https://www.jiit.ac.in/uploads/economic_7_b51e85efdc.webp",
      "https://www.jiit.ac.in/uploads/economic_6_1_6b9720d14b.webp",
      "https://www.jiit.ac.in/uploads/econoic_2_25fc5ac7ed.webp",
      "https://www.jiit.ac.in/uploads/economic_5_e214c0f989.webp",
      "https://www.jiit.ac.in/uploads/econmic_1_ac4c8a81ab.webp",
      "https://www.jiit.ac.in/uploads/economic_6_84074262a5.webp",
      "https://www.jiit.ac.in/uploads/economics_3_a4495f1188.webp"
    ]
  },
  {
    "id": "giwm",
    "name": "GIWM",
    "fullName": "Green Initiatives & Waste Management Cell",
    "description": "JIIT Noida's central body for promoting sustainability, environmental responsibility, and effective waste management practices.",
    "fullDescription": "The Green Initiatives & Waste Management Cell (GIWM) at JIIT Noida is the institute's central body for promoting sustainability, environmental responsibility, and effective waste management practices. GIWM fosters ecological responsibility and sustainable campus living.",
    "category": "Social",
    "icon": "Leaf",
    "color": "from-green-500 to-lime-500",
    "iconColor": "text-green-400",
    "image": "https://www.jiit.ac.in/uploads/img_419c7cf25e.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/giwm",
    "gallery": [
      "https://www.jiit.ac.in/uploads/Picture5_1d9d3bf85b.png",
      "https://www.jiit.ac.in/uploads/Picture5_781b0dba8b.png",
      "https://www.jiit.ac.in/uploads/Picture3_aae08ff77b.png",
      "https://www.jiit.ac.in/uploads/Picture24_73c47b2b57.png",
      "https://www.jiit.ac.in/uploads/Picture25_2044b2b9d8.png",
      "https://www.jiit.ac.in/uploads/Picture18_df5cb83fcf.png",
      "https://www.jiit.ac.in/uploads/Picture17_0b0579d0ab.png",
      "https://www.jiit.ac.in/uploads/Picture20_93967866c4.png",
      "https://www.jiit.ac.in/uploads/Picture19_287df429c6.png",
      "https://www.jiit.ac.in/uploads/Picture10_0f35dd594a.png",
      "https://www.jiit.ac.in/uploads/Picture7_d0889b753f.png",
      "https://www.jiit.ac.in/uploads/Picture12_1f0fc7f3cc.png",
      "https://www.jiit.ac.in/uploads/Picture4_5608f4b0f9.png",
      "https://www.jiit.ac.in/uploads/Picture16_1091e18776.png",
      "https://www.jiit.ac.in/uploads/Picture23_eefd8ec658.png",
      "https://www.jiit.ac.in/uploads/Picture8_23ef5fc2fa.png",
      "https://www.jiit.ac.in/uploads/Picture22_e2d9910991.png",
      "https://www.jiit.ac.in/uploads/Picture15_6adc85c419.png",
      "https://www.jiit.ac.in/uploads/Picture9_59ddcfbb4e.png",
      "https://www.jiit.ac.in/uploads/Picture1_d341e66cd9.png",
      "https://www.jiit.ac.in/uploads/Picture14_2deaf98f7f.png",
      "https://www.jiit.ac.in/uploads/Picture11_d31f26fb58.png",
      "https://www.jiit.ac.in/uploads/Picture26_0307b79ba5.png",
      "https://www.jiit.ac.in/uploads/Picture21_d8c05b9a83.png",
      "https://www.jiit.ac.in/uploads/Picture2_939eda42ff.png",
      "https://www.jiit.ac.in/uploads/Picture13_519b55dbbb.png",
      "https://www.jiit.ac.in/uploads/Picture6_4894914a22.png"
    ]
  },
  {
    "id": "consulting",
    "name": "Consulting Hub",
    "fullName": "The Consulting Hub",
    "description": "A lively space where curious and ambitious students come together to explore ideas, learn new skills, and tackle real-world business challenges.",
    "fullDescription": "The Consulting Hub at Jaypee Business School has quickly grown into a lively space where curious and ambitious students come together to explore ideas, learn new skills, and tackle real-world business challenges. The hub provides platforms for case study competitions, consulting projects, and professional development.",
    "category": "Social",
    "icon": "Briefcase",
    "color": "from-blue-500 to-indigo-500",
    "iconColor": "text-blue-400",
    "image": "https://www.jiit.ac.in/uploads/img_a4897dad2c.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/the-consulting-hub",
    "gallery": [
      "https://www.jiit.ac.in/uploads/7_544c2715dc.png",
      "https://www.jiit.ac.in/uploads/15_8ef012701e.jpg",
      "https://www.jiit.ac.in/uploads/16_df9f4cbecf.jpg",
      "https://www.jiit.ac.in/uploads/14_55fa99312f.jpg",
      "https://www.jiit.ac.in/uploads/10_d2578e52ee.jpg",
      "https://www.jiit.ac.in/uploads/13_9ae81947a7.jpg",
      "https://www.jiit.ac.in/uploads/11_216f0d91a7.jpg",
      "https://www.jiit.ac.in/uploads/9_ef4689a3f2.jpg",
      "https://www.jiit.ac.in/uploads/4_f622f8b93d.png",
      "https://www.jiit.ac.in/uploads/12_f02efb9a4a.jpg",
      "https://www.jiit.ac.in/uploads/5_f406aa9165.png",
      "https://www.jiit.ac.in/uploads/6_44b24dbb95.png",
      "https://www.jiit.ac.in/uploads/8_c576423d1e.png",
      "https://www.jiit.ac.in/uploads/18_96d024f920.jpg",
      "https://www.jiit.ac.in/uploads/3_ebe01641cf.png",
      "https://www.jiit.ac.in/uploads/19_4b74426f71.jpg",
      "https://www.jiit.ac.in/uploads/7_8137fb9591.png",
      "https://www.jiit.ac.in/uploads/20_e7d9ff44a6.jpg",
      "https://www.jiit.ac.in/uploads/17_9847af330a.jpg",
      "https://www.jiit.ac.in/uploads/2_342e6a2887.png",
      "https://www.jiit.ac.in/uploads/1_b424d27a6d.png"
    ]
  },
  {
    "id": "hruday",
    "name": "HRUDAY",
    "fullName": "The HR Club",
    "description": "Founded with the vision of nurturing future HR leaders, serving as a platform to explore the dynamic world of Human Resource Management.",
    "fullDescription": "HRUDAY was founded with the vision of nurturing future HR leaders. It serves as a platform where students can explore the dynamic world of Human Resource Management beyond the classroom. The club organizes workshops, panel discussions, and simulations to develop HR competencies.",
    "category": "Social",
    "icon": "Heart",
    "color": "from-pink-500 to-rose-500",
    "iconColor": "text-pink-400",
    "image": "https://www.jiit.ac.in/uploads/img_d080ca055d.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/hruday-thehrclub",
    "gallery": [
      "https://www.jiit.ac.in/uploads/1_3a81b938da.png",
      "https://www.jiit.ac.in/uploads/4_a19f5535c5.png",
      "https://www.jiit.ac.in/uploads/5_da2727d7ae.png",
      "https://www.jiit.ac.in/uploads/1_52a3cf0c0f.png",
      "https://www.jiit.ac.in/uploads/2_aaa5cf9756.png",
      "https://www.jiit.ac.in/uploads/3_80f70d8479.png"
    ]
  },
  {
    "id": "mind",
    "name": "MIND",
    "fullName": "Multidisciplinary Initiative for Nuance and Deliberation",
    "description": "A student-led intellectual initiative that promotes research-oriented discussion and informed civic thinking.",
    "fullDescription": "The Multidisciplinary Initiative for Nuance and Deliberation (MIND) is a student-led intellectual initiative at Jaypee Institute of Information Technology that promotes research-oriented discussion and informed civic thinking. MIND encourages critical analysis, academic debate, and interdisciplinary exploration.",
    "category": "Social",
    "icon": "Brain",
    "color": "from-violet-500 to-purple-500",
    "iconColor": "text-violet-400",
    "image": "https://www.jiit.ac.in/uploads/img_211d33c3af.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/multidisciplinary-initiative-for-nuance-and-deliberation",
    "gallery": [
      "https://www.jiit.ac.in/uploads/2_313bcf62c9.jpg",
      "https://www.jiit.ac.in/uploads/1_2cbda7f1bf.jpg",
      "https://www.jiit.ac.in/uploads/2_e5ab8cc7dd.jpg",
      "https://www.jiit.ac.in/uploads/4_90c25fda59.jpg",
      "https://www.jiit.ac.in/uploads/3_a8f4bc6f51.jpg"
    ]
  },
  {
    "id": "finanza",
    "name": "Finanza",
    "fullName": "The Finance Club of JBS",
    "description": "A vibrant community that brings together students eager to explore the world of finance, economics, and business strategy.",
    "fullDescription": "Finanza, the finance club of JBS, is a vibrant community that brings together students who are eager to explore the world of finance, economics, and business strategy. The club organizes events like stock market simulations, financial literacy workshops, and investment competitions.",
    "category": "Social",
    "icon": "TrendUp",
    "color": "from-emerald-500 to-cyan-500",
    "iconColor": "text-emerald-400",
    "image": "https://www.jiit.ac.in/uploads/finanaza_thumb_985163e68b.webp",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/finanza-the-finance-club-of-jbs",
    "gallery": [
      "https://www.jiit.ac.in/uploads/image_3e42fd093c.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_10_08_at_18_25_13_d2624dc5_885cc7a23f.jpg",
      "https://www.jiit.ac.in/uploads/Whats_App_Image_2025_10_08_at_18_25_13_d7f3fc13_935499a23f.jpg",
      "https://www.jiit.ac.in/uploads/F_6_1_a3853e0b5a.webp",
      "https://www.jiit.ac.in/uploads/f_3_d07a1b6283.webp",
      "https://www.jiit.ac.in/uploads/F_6_2b7ee20070.webp",
      "https://www.jiit.ac.in/uploads/f_2_969d76022a.webp"
    ]
  },
  {
    "id": "yoga",
    "name": "Yoga Hub",
    "fullName": "Yoga, Prahari & Health Hub",
    "description": "Working towards a healthy and stress-free student life covering all wellness aspects \u2014 physical, emotional, and spiritual.",
    "fullDescription": "The Yoga, Prahari and Health Hub at Jaypee Institute of Information Technology, Noida is working towards a healthy and stress-free student life covering all wellness aspects \u2014 physical, emotional, and spiritual. Conducts regular yoga sessions and 'Prahari' drug awareness campaigns via nukkad natak.",
    "category": "Health & Wellness",
    "icon": "Activity",
    "color": "from-teal-500 to-green-500",
    "iconColor": "text-teal-400",
    "image": "https://www.jiit.ac.in/uploads/yoga_prahari_health_hub_4413002d37.jpg",
    "jiitUrl": "https://www.jiit.ac.in/existing-student/life-@-jiit/jiit-hub/yoga-prahari-and-health-hub",
    "gallery": []
  },
  {
    "id": "bitwise",
    "name": "Bit-Wise",
    "fullName": "The Bit-Wise Programming Club",
    "description": "Dedicated to competitive programming and DSA at Sector 128. Organizes weekly code classes and the high-pressure 'KODEATHON'.",
    "fullDescription": "Dedicated to competitive programming and DSA at Sector 128. Organizes weekly code classes and the high-pressure 'KODEATHON'.",
    "category": "Technical",
    "icon": "Code",
    "color": "from-blue-500 to-cyan-500",
    "iconColor": "text-blue-400",
    "campus": "128"
  },
  {
    "id": "cicr",
    "name": "CICR",
    "fullName": "Creative & Innovative Cell in Robotics",
    "description": "Premier technical club at JIIT Sector-128, Noida, focused on robotics research, electronics design, and prototyping.",
    "fullDescription": "Premier technical club at JIIT Sector-128, Noida, focused on robotics research, electronics design, and prototyping.",
    "category": "Technical",
    "icon": "Robot",
    "color": "from-orange-500 to-red-500",
    "iconColor": "text-orange-400",
    "campus": "128",
    "socials": {
      "website": "https://www.cicr.in/",
      "instagram": "https://www.instagram.com/cicr_jiit/",
      "linkedin": "https://www.linkedin.com/company/cicrjiit128/"
    }
  },
  {
    "id": "eloquence",
    "name": "Eloquence",
    "fullName": "Literary Society of JIIT",
    "description": "Education Literary Hub at Jaypee Institute of Information Technology, Sector 128, Noida.",
    "fullDescription": "Education Literary Hub at Jaypee Institute of Information Technology, Sector 128, Noida.",
    "category": "Literary",
    "icon": "BookOpen",
    "color": "from-blue-400 to-indigo-500",
    "iconColor": "text-blue-400",
    "campus": "128"
  }
];
